Repository yasa-org/yasa, pull requests merged in 2020-07, with the labels that each got.

#27 BugFix: failed to create collection with empty `createNodeSet`
  yasa-ui/src/components/management/NewCollectionForm.vue
  yasa-ui/src/service/solr/collections/index.ts
  yasa-ui/src/store/modules/management/collections.ts
Labels: bug

#26 Feature: add menu to get back to legacy UI
  yasa-ui/src/App.vue
  yasa-ui/src/i18n.ts
  yasa-ui/src/store/index.ts
  yasa-ui/vue.config.js
Labels: enhancement

#28 Feature: replace ace-editor with monaco-editor
  yasa-ui/package-lock.json
  yasa-ui/package.json
  yasa-ui/src/components/dev-tools/DevTools.vue
  yasa-ui/src/components/dev-tools/code-editor/AceEditor.vue
  yasa-ui/src/components/dev-tools/code-editor/CodeEditor.ts
  yasa-ui/src/components/dev-tools/code-editor/CodeEditor.vue
  yasa-ui/src/components/management/ConfigSets.vue
  yasa-ui/src/components/management/Tree.vue
  yasa-ui/src/main.ts
  yasa-ui/src/router/index.ts
  yasa-ui/src/store/modules/dev-tools/index.ts
  yasa-ui/src/style/common.scss
  yasa-ui/src/style/element-variables.scss
  yasa-ui/src/style/normalize.css
  yasa-ui/src/style/style.scss
  yasa-ui/vue.config.js
Labels: enhancement

#31 Package manager fixes and docs
  README.adoc
  pom.xml
  yasa-solr-plugin/pom.xml
  yasa-solr-plugin/src/main/java/io/github/kezhenxu94/YasaHandler.java
  yasa-solr-plugin/src/main/resources/manifest.json
  yasa-ui/pom.xml
Labels: enhancement

#32 Fix CSP restrictions
  yasa-ui/.eslintignore
  yasa-ui/public/index.html
  yasa-ui/src/App.vue
  yasa-ui/src/style/iconfont/iconfont.css
  yasa-ui/src/style/iconfont/iconfont.eot
  yasa-ui/src/style/iconfont/iconfont.js
  yasa-ui/src/style/iconfont/iconfont.json
  yasa-ui/src/style/iconfont/iconfont.svg
  yasa-ui/src/style/iconfont/iconfont.ttf
  yasa-ui/src/style/iconfont/iconfont.woff
  yasa-ui/src/style/iconfont/iconfont.woff2
  yasa-ui/vue.config.js
Labels: enhancement

#33 Feature: add thread dump page
  yasa-ui/src/App.vue
  yasa-ui/src/components/management/Collections.vue
  yasa-ui/src/components/thread-dump/ThreadDumpItem.vue
  yasa-ui/src/components/thread-dump/ThreadDumpView.vue
  yasa-ui/src/i18n.ts
  yasa-ui/src/router/index.ts
  yasa-ui/src/service/solr/admin/info/index.ts
  yasa-ui/src/style/common.scss
  yasa-ui/src/style/iconfont/iconfont.css
  yasa-ui/src/style/iconfont/iconfont.eot
  yasa-ui/src/style/iconfont/iconfont.js
  yasa-ui/src/style/iconfont/iconfont.json
  yasa-ui/src/style/iconfont/iconfont.svg
  yasa-ui/src/style/iconfont/iconfont.ttf
  yasa-ui/src/style/iconfont/iconfont.woff
  yasa-ui/src/style/iconfont/iconfont.woff2
Labels: feature
